### ISSUE TITLE
User Story 4 - Simple landingpage for the app

### ISSUE THREAD

**Issue by kwoide** [kwoide/capstone-project#10]
# Value Proposition

**As a** user
**I want to** see a landingpage
**So that** I can navigate to the page where I want to go

# Description

![Image](https://user-images.githubusercontent.com/107850294/188311065-099021a8-6aa8-44a6-a4fa-184c8f7a80bb.png)

# Acceptance Criteria

- [x] A lottie animation should be visible at first glance.
- [x] There are two different buttons. Since the app is aimed at B2B but also B2C customers, you have to be able to select which area is of interest to you.

# Tasks

- [x] Create a new branch
- [x] Add a Lottie animation
- [x] Add two buttons 

# Complexity

M
