### ISSUE TITLE
User Story 5 - Styling

### ISSUE THREAD

**Issue by kwoide** [kwoide/capstone-project#11]
# Value Proposition

**As a** user
**I want to** have a styled application
**So that** I have a better user experience

# Description

![Image](https://user-images.githubusercontent.com/107850294/188422850-f32c0cae-406d-4e48-bb8b-31c5a329a105.png)

# Acceptance Criteria

- [ ] the app should have a consistent design
- [ ] The format of the app should refer to the iPhone SE
- [ ] There should be subtle animations in the design of the app. 

# Tasks

- [ ] Create a new branch
- [ ] Add styling to the elements 
- [ ] Add animations

# Complexity

L
