### ISSUE TITLE
Create a form with a submit button

### ISSUE THREAD

**Issue by kwoide** [kwoide/capstone-project#2]
# Value Proposition

**As a** user
**I want to** add a single restaurant
**So that**  I can collect my restaurants

# Description

![Image](https://user-images.githubusercontent.com/107850294/186429269-335dc3ef-7ac3-4f24-8b6f-d0c6e8daac9a.png)

# Acceptance Criteria

- [x] The input fields are the name of the restaurant, type of food and the price level of the food
- [x] By clicking on the submit button the new menu is added to a list below the form.
- [x] All input fields shall be mandatory fields. If the user forgets to fill in one of these fields, he will receive an error message stating that there are still fields to be filled in. 

# Tasks

- [x] Create a new branch
- [x] Connect app with vercel
- [x] Check linting settings and adjust if necessary
- [x] Deal with react hook form
- [x] Create a Form component with three input fields
- [x] Add a submit button to the form

# Complexity

L

**Comment by Gw3i** [comment]
Hello Kolja!

Great User Story.
I would change some things.
First,  upload a scribble without the navigation, just the form.
Second, you should write the acceptance criteria accurately what should be shown, because "Two to three input fields..." sounds not precise.
You should also not mention what should happen in the future implementation because it's not part of the user story.
Lastly, I would write the tasks more precise, because that will help you in the implementation.

**Comment by kwoide** [comment]
Hey Vlady,

Thank you very much for this detailed feedback. I have now revised the points you raised and would be happy to receive further feedback.

**Comment by RobertBReich** [comment]
Hey Kolja,
looks good.

**Comment by kwoide** [comment]
> Hey Kolja, looks good.

Hello Robert, 

thank you for the feedback.

**Comment by JessicaLoers** [comment]
**Hi @kwoide** 👋

I'm super duper mean 👿 and have additional comments 😁

**Value Proposition** please be more precise regarding the User's value and perspective of this feature 
> As a user
I want to have a form - **_This should be more an activity_**
So that I can enter various data - **_the User's desired value of this feature_**

Here are some examples: 
**As a user**
**I want to** add/create my own/a single menu  ...
**So that I can** collect my menus / have a list my favorite menus ...

**Acceptance Criteria**
- What happens after the user submit the form? Where are your entries displayed? 
- What happens if the user submit the form without the required input fields? Is an error message displayed?

>  The input field is required - **Actually this is not a AC from the user's perspective, the user doesn't care about the required fields**

I would recommend that you write a separate user story for the local storage feature - you don't need this for now. 
Rather render you entry in a simple list below your form. 

**By the way -  Please change your project board to public** 😉

**Comment by kwoide** [comment]
Hello Jessica, 

Thank you very much for the detailed feedback. I have now revised the user story and hope that it will be accepted.

**Comment by j-eick** [comment]
I like it. 👍🏼 A few details:

### AC

> _"A heading should be visible at first glance"_

➡️ Try not to use "could/should/would". 
**_Instead:_** A heading **is** visible at first glance

> _"The input fields are the name of the restaurant, type of food and culinary variety"_

➡️ What's meant by "culinary variety"?

### Tasks

> _"edit linting"_

➡️ I would specify this a bit more, but you do you. :)

> _"Add form validation"_

➡️ I would be more specific here. How do you want to validate... etc. But again... you do you.

**Comment by kwoide** [comment]
Hello Joschka, 

Thank you very much for your detailed feedback. I have now updated the user story and changed the following points. 

### Description

➡️ I have updated the scribble and adapted it to the new circumstances.

### AC

➡️ I have implemented the note with the headline

➡️ I have changed the input field Culinary Variety. Now you can choose the price level by dropdown. 

### Tasks

➡️ The task with the linting was rephrased

➡️ Form validation is moved to another user story


@j-eick

**Comment by ahohnsen** [comment]
Hey Kolja,

As Jessica already said, I think it would be good to be a bit more specific in your acceptance criteria: 

> 
> What happens after the user submit the form? Where are your entries displayed?

Example: By clicking on the submit button the new menu is added to a list below the form. (It would be also nice to see this in the scribble).

> What happens if the user submit the form without the required input fields? Is an error message displayed?

As Jessica mentions in her previous comment, it would be best if there is an indication that an input field is required (e.g. with a *). You should think about what happens if not all required input fields are filled. The user will need some kind of visual feedback, so that he/she knows what to do next. This scenario should be described in your acceptance criteria as well.

All the things which are visible in the scribble, you do not need to mention again in your acceptance criteria (e.g. there is a heading, a button etc.).

**Comment by Gw3i** [comment]
Hey Kolja,
really good User Story!
There are just two typos:
In AC  the last field -> The entered data will be saved **in** a simple list below the form
In Tasks 3rd field, to keep it consistent ->  **D**eal with react hook form
