### ISSUE TITLE
User Story #2 - Add a form where a user can add a single dish

### ISSUE THREAD

**Issue by kwoide** [kwoide/capstone-project#6]
# Value Proposition

**As a** user
**I want to** add a dish
**So that** i can collect different dishes

# Description

![Image](https://user-images.githubusercontent.com/107850294/187142995-d4b60dfe-848a-44d7-aa77-6747b2605ca2.png)

# Acceptance Criteria

- [ ] The input fields are the name of the dish, price, category and description
- [ ] By clicking on the submit button the new dish is added to a list below the form.
- [ ]  All input fields shall be mandatory fields. If the user forgets to fill in one of these fields, he will receive an error message stating that there are still fields to be filled in.

# Tasks

- [ ] Create a new branch
- [ ] Create a new form component
- [ ] Add a new form with react-hook-forms
- [ ] Add a submit button

# Complexity

M

**Comment by Mersag** [comment]
Hi Kolja, 
ich finde es sehr klar, was du erreichen möchtest. 
1. Allerdings, wäre ich User deiner fantastischen App wüsste ich nicht, was in **Deskription:  "extern und intern" gemeint ist** Es sei denn, ich klicke und sehe und erfahre.
2. Deine User Story ,würde ich demnach auch etwas anpassen.
 
Ich freue mich schon auf deine App :-)

**Comment by kwoide** [comment]
Hello Meral, thank you for your feedback. I will adapt the user story now.

**Comment by ckskr** [comment]
Hi Kolja, 
looks good! 
I am not sure if as a user I would understand the difference between "guest" and "owner"... Maybe you could add each one small sentence like "You are hungry? Click here to browser through you favorite restaurants menus" (for the user)

**Comment by Mersag** [comment]
Hey Kolja, I see you changed your description **"external and internal "** to **"guest and owner"** ... Wenn du heute etwas Zeit hast, dann lass uns kurz besprechen, was du erreichen willst.

**Comment by kwoide** [comment]
> Hi Kolja,
> looks good!
> I am not sure if as a user I would understand the difference between "guest" and "owner"... Maybe you could add each one small sentence like "You are hungry? Click here to browser through you favorite restaurants menus" (for the user)

Hello Claudia, thank you for your feedback. I will update the user story.
