### ISSUE TITLE
User Story 3

### ISSUE THREAD

**Issue by kwoide** [kwoide/capstone-project#9]
# Value Proposition

**As a** user
**I want to** i want to have a page 
**So that** i can see the different restaurants

# Description

![Image](https://user-images.githubusercontent.com/107850294/187184811-d50cab3e-1ea2-4572-8126-5f271d6ff5b1.png)

# Acceptance Criteria

- [ ] on one page the different restaurants should be displayed as a card
- [ ] when you click on a card, a detail page of the restaurant should be opened

# Tasks

- [ ] Create a new branch
- [ ] Create a card component

# Complexity

L

**Comment by A11yship** [comment]
Looks good. I only would add two word:
" i want to have a restaurant overview page "
So it is more clear what page it is.
